### PR TITLE
fix: broken drawer

### LINKED ISSUE #108: Drawer component is very broken on mobile
### Describe the bug

The Drawer in the @next version breaks inputs on mobile making the keyboard open and close in a very strange way

### Reproduction

It happens in the documentation example itself
https://next.shadcn-svelte.com/docs/components/drawer#responsive-dialog

https://github.com/user-attachments/assets/e1703f30-01ab-4a93-a17d-3fa909a1b6fe

### Logs

_No response_

### System Info

```bash
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics

    Memory: 5.46 GB / 13.80 GB
  Binaries:
    Node: 22.11.0 - ~\AppData\Local\fnm_multishells\2244_1732287129630\node.EXE
    npm: 10.9.0 - ~\AppData\Local\fnm_multishells\2244_1732287129630\npm.CMD
    bun: 1.1.36 - ~\.bun\bin\bun.EXE
  Browsers: {}
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.8.1
    bits-ui: ^1.0.0-next.63 => 1.0.0-next.63
    lucide-svelte: ^0.460.1 => 0.460.1
    mode-watcher: ^0.5.0 => 0.5.0
    svelte: ^5.0.0 => 5.1.16
    svelte-sonner: ^0.3.28 => 0.3.28
    vaul-svelte: 1.0.0-next.3 => 1.0.0-next.3
```

### Severity

blocking an upgrade

### PR DESCRIPTION
**Pull request by huntabyte**
Still need to get the snap points drawer on certain devices to close properly under certain conditions, but merging these updates as they alleviate some other issues people are having.

### CODE REVIEW

**Comment by PolpOnline** [comment]
I know you are still working on this, but I installed 
ca68d71 and it worked like a charm

**Comment by huntabyte** [comment]
Awesome @PolpOnline ! There is one little issue I'm trying to work out with the first snap point glitching a bit when being closed without going to a second snap point!

**Comment by PolpOnline** [comment]
Yeah I'm having issues too with the usage of the drawer when the size of the input items exceeds the space size, here is a video of that:


https://github.com/user-attachments/assets/78e929d5-c3aa-430c-8489-daeb6977cc3c



It is kind of difficult to tell whats going on with just a video of it but you can try them yourself at [monitor.polp.online](https://monitor.polp.online) ([this is the repo](https://github.com/PolpOnline/monitor)).

**Comment by PolpOnline** [comment]
Another thing that I would add is that as you can see the background shrinking is not working

File: packages/vaul-svelte/src/lib/components/drawer/drawer-content.svelte [hunk 1]
```diff
@@ -28,25 +28,33 @@
...
+
+	const mergedProps = $derived(
+		mergeProps(restProps, contentState.props, { style: styleProp })
+		// eslint-disable-next-line @typescript-eslint/no-explicit-any
+	) as any;
 </script>
 
-<DialogPrimitive.Content
-	{...mergedProps}
-	{preventScroll}
```
Comment (kevinmsun) [inline packages/vaul-svelte/src/lib/components/drawer/drawer-content.svelte]: I'm observing that with this removed, body scroll seems to be *always* disabled when the drawer is open, presumably since the absence of this property (which defaults to `true` in bits) triggers the underlying bits component to do the scroll-lock independent of the control in this component

If this isn't intentional, it feels like maybe this should infer something derived from `disablePreventScroll`?

File: packages/vaul-svelte/src/lib/use-drawer-content.svelte.ts [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+		"data-vaul-animate": ctx.shouldAnimate ? "true" : "false",
+		onpointerdown,
+		onOpenAutoFocus,
+		onInteractOutside,
+		onFocusOutside,
+		onpointerup,
+		onpointermove,
+		onpointerout,
+		oncontextmenu,
+		preventScroll: ctx.modal.current,
```
Comment (kevinmsun) [inline packages/vaul-svelte/src/lib/use-drawer-content.svelte.ts:188]: I'm observing that with this change, body scroll seems to be **_always_** disabled when the drawer is open

should this should infer something derived from `disablePreventScroll` in addition to what it already uses?

Comment (kevinmsun) [reply packages/vaul-svelte/src/lib/use-drawer-content.svelte.ts:188]: ignore me - i was referencing the wrong version of documentation and didn't realize that `modal` *itself* was a prop that can be used to control this behavior. thanks!
